// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.34.1
// source: src/proto/subscription.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "subscription";

export interface GetSubscriptionRequest {
  subscriptionId: string;
}

export interface SubscriptionResponse {
  id: string;
  userId: string;
  planId: string;
  status: string;
  currentPeriodStart: Timestamp | undefined;
  currentPeriodEnd: Timestamp | undefined;
  cancelAtPeriodEnd: boolean;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export interface GetUserActiveSubscriptionsRequest {
  userId: string;
}

export interface GetUserActiveSubscriptionsResponse {
  subscriptions: SubscriptionResponse[];
}

export const SUBSCRIPTION_PACKAGE_NAME = "subscription";

function createBaseGetSubscriptionRequest(): GetSubscriptionRequest {
  return { subscriptionId: "" };
}

export const GetSubscriptionRequest: MessageFns<GetSubscriptionRequest> = {
  encode(message: GetSubscriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriptionId !== "") {
      writer.uint32(10).string(message.subscriptionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSubscriptionResponse(): SubscriptionResponse {
  return {
    id: "",
    userId: "",
    planId: "",
    status: "",
    currentPeriodStart: undefined,
    currentPeriodEnd: undefined,
    cancelAtPeriodEnd: false,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const SubscriptionResponse: MessageFns<SubscriptionResponse> = {
  encode(message: SubscriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.planId !== "") {
      writer.uint32(26).string(message.planId);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.currentPeriodStart !== undefined) {
      Timestamp.encode(message.currentPeriodStart, writer.uint32(42).fork()).join();
    }
    if (message.currentPeriodEnd !== undefined) {
      Timestamp.encode(message.currentPeriodEnd, writer.uint32(50).fork()).join();
    }
    if (message.cancelAtPeriodEnd !== false) {
      writer.uint32(56).bool(message.cancelAtPeriodEnd);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(66).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(message.updatedAt, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.planId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currentPeriodStart = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currentPeriodEnd = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.cancelAtPeriodEnd = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserActiveSubscriptionsRequest(): GetUserActiveSubscriptionsRequest {
  return { userId: "" };
}

export const GetUserActiveSubscriptionsRequest: MessageFns<GetUserActiveSubscriptionsRequest> = {
  encode(message: GetUserActiveSubscriptionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveSubscriptionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveSubscriptionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserActiveSubscriptionsResponse(): GetUserActiveSubscriptionsResponse {
  return { subscriptions: [] };
}

export const GetUserActiveSubscriptionsResponse: MessageFns<GetUserActiveSubscriptionsResponse> = {
  encode(message: GetUserActiveSubscriptionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.subscriptions) {
      SubscriptionResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserActiveSubscriptionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserActiveSubscriptionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriptions.push(SubscriptionResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface SubscriptionServiceClient {
  getSubscription(request: GetSubscriptionRequest): Observable<SubscriptionResponse>;

  getUserActiveSubscriptions(
    request: GetUserActiveSubscriptionsRequest,
  ): Observable<GetUserActiveSubscriptionsResponse>;
}

export interface SubscriptionServiceController {
  getSubscription(
    request: GetSubscriptionRequest,
  ): Promise<SubscriptionResponse> | Observable<SubscriptionResponse> | SubscriptionResponse;

  getUserActiveSubscriptions(
    request: GetUserActiveSubscriptionsRequest,
  ):
    | Promise<GetUserActiveSubscriptionsResponse>
    | Observable<GetUserActiveSubscriptionsResponse>
    | GetUserActiveSubscriptionsResponse;
}

export function SubscriptionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getSubscription", "getUserActiveSubscriptions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SubscriptionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SubscriptionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SUBSCRIPTION_SERVICE_NAME = "SubscriptionService";

export type SubscriptionServiceService = typeof SubscriptionServiceService;
export const SubscriptionServiceService = {
  getSubscription: {
    path: "/subscription.SubscriptionService/GetSubscription",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetSubscriptionRequest): Buffer =>
      Buffer.from(GetSubscriptionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSubscriptionRequest => GetSubscriptionRequest.decode(value),
    responseSerialize: (value: SubscriptionResponse): Buffer =>
      Buffer.from(SubscriptionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscriptionResponse => SubscriptionResponse.decode(value),
  },
  getUserActiveSubscriptions: {
    path: "/subscription.SubscriptionService/GetUserActiveSubscriptions",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserActiveSubscriptionsRequest): Buffer =>
      Buffer.from(GetUserActiveSubscriptionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserActiveSubscriptionsRequest =>
      GetUserActiveSubscriptionsRequest.decode(value),
    responseSerialize: (value: GetUserActiveSubscriptionsResponse): Buffer =>
      Buffer.from(GetUserActiveSubscriptionsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserActiveSubscriptionsResponse =>
      GetUserActiveSubscriptionsResponse.decode(value),
  },
} as const;

export interface SubscriptionServiceServer extends UntypedServiceImplementation {
  getSubscription: handleUnaryCall<GetSubscriptionRequest, SubscriptionResponse>;
  getUserActiveSubscriptions: handleUnaryCall<GetUserActiveSubscriptionsRequest, GetUserActiveSubscriptionsResponse>;
}

export interface SubscriptionServiceClient extends Client {
  getSubscription(
    request: GetSubscriptionRequest,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscription(
    request: GetSubscriptionRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getSubscription(
    request: GetSubscriptionRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SubscriptionResponse) => void,
  ): ClientUnaryCall;
  getUserActiveSubscriptions(
    request: GetUserActiveSubscriptionsRequest,
    callback: (error: ServiceError | null, response: GetUserActiveSubscriptionsResponse) => void,
  ): ClientUnaryCall;
  getUserActiveSubscriptions(
    request: GetUserActiveSubscriptionsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUserActiveSubscriptionsResponse) => void,
  ): ClientUnaryCall;
  getUserActiveSubscriptions(
    request: GetUserActiveSubscriptionsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUserActiveSubscriptionsResponse) => void,
  ): ClientUnaryCall;
}

export const SubscriptionServiceClient = makeGenericClientConstructor(
  SubscriptionServiceService,
  "subscription.SubscriptionService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SubscriptionServiceClient;
  service: typeof SubscriptionServiceService;
  serviceName: string;
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
